<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;

class Word extends Model
{
    public $timestamps = false;
    public static $count_contractions = 0;
    public static $count_badwords= 0;

    static public $words = array();

    /**
     * Get the lemma word.
     */
    public function lemma()
    {
        return $this->hasOne('App\Word','lemma_word_id');
    }

    /*
     * Returns the number of words equals to 20% of the total
     * @return integer
     */
    public static function get20Count() {
        $count20 = ceil((DB::table('words')->count()*20)/100);

        return $count20;
    }

    public static function get20Words() {
        if(!empty(self::$words)) {
            return self::$words;
        }
        return self::$words = Word::where(array())->orderBy('frequence','desc')->take(Word::get20Count())->get();         

    }

    public static function reverseEnglishContractions($text) {
        $iReplaced = $iBadWords = 0;
        $count = 0;
        $contractions = array (
         "cannot" => "can not",
         "ain't" =>"am not",
         "aren't" =>"are not",
         "can't" =>"cannot",
         "can't've" =>"cannot have",
         "'cause" =>"because",
         "could've" =>"could have",
         "couldn't" =>"could not",
         "couldn't've" =>"could not have",
         "didn't" =>"did not",
         "doesn't" =>"does not",
         "don't" =>"do not",
         "hadn't" =>"had not",
         "hadn't've" =>"had not have",
         "hasn't" =>"has not",
         "haven't" =>"have not",
         "he'd" =>"he had",
         "he'd've" =>"he would have",
         "he'll" =>"he shall",
         "he'll've" =>"he will have",
         "he's" =>"he is",
         "how'd" =>"how did",
         "how'd'y" =>"how do you",
         "how'll" =>"how will",
         "how's" =>"how is",
         "I'd" =>"I would",
         "I'd've" =>"I would have",
         "I'll" =>"I will",
         "I'll've" =>"I will have",
         "I'm" =>"I am",
         "I've" =>"I have",
         "isn't" =>"is not",
         "it'd" =>"it would",
         "it'd've" =>"it would have",
         "it'll" =>"it will",
         "it'll've" =>"it will have",
         "it's" =>"it is",
         "let's" =>"let us",
         "ma'am" =>"madam",
         "mayn't" =>"may not",
         "might've" =>"might have",
         "mightn't" =>"might not",
         "mightn't've" =>"might not have",
         "must've" =>"must have",
         "mustn't" =>"must not",
         "mustn't've" =>"must not have",
         "needn't" =>"need not",
         "needn't've" =>"need not have",
         "o'clock" =>"of the clock",
         "oughtn't" =>"ought not",
         "oughtn't've" =>"ought not have",
         "shan't" =>"shall not",
         "sha'n't" =>"shall not",
         "shan't've" =>"shall not have",
         "she'd" =>"she would",
         "she'd've" =>"she would have",
         "she'll" =>"she will",
         "she'll've" =>"she will have",
         "she's" =>"she is",
         "should've" =>"should have",
         "shouldn't" =>"should not",
         "shouldn't've" =>"should not have",
         "so've" =>"so have",
         "so's" =>"so is",
         "that'd" =>"that had",
         "that'd've" =>"that would have",
         "that's" =>"that is",
         "there'd" =>"there would",
         "there'd've" =>"there would have",
         "there's" =>"there is",
         "they'd" =>"they would",
         "they'd've" =>"they would have",
         "they'll" =>"they will",
         "they'll've" =>"they will have",
         "they're" =>"they are",
         "they've" =>"they have",
         "to've" =>"to have",
         "wasn't" =>"was not",
         "we'd" =>"we would",
         "we'd've" =>"we would have",
         "we'll" =>"we will",
         "we'll've" =>"we will have",
         "we're" =>"we are",
         "we've" =>"we have",
         "weren't" =>"were not",
         "what'll" =>"what will",
         "what'll've" =>"what will have",
         "what're" =>"what are",
         "what's" =>"what is",
         "what've" =>"what have",
         "when's" =>"when is",
         "when've" =>"when have",
         "where'd" =>"where did",
         "where's" =>"where is",
         "where've" =>"where have",
         "who'll" =>"who will",
         "who'll've" =>"who will have",
         "who's" =>"who is",
         "who've" =>"who have",
         "why's" =>"why is",
         "why've" =>"why have",
         "will've" =>"will have",
         "won't" =>"will not",
         "won't've" =>"will not have",
         "would've" =>"would have",
         "wouldn't" =>"would not",
         "wouldn't've" =>"would not have",
         "y'all" =>"you all",
         "y'all'd" =>"you all would",
         "y'all'd've" =>"you all would have",
         "y'all're" =>"you all are",
         "y'all've" =>"you all have",
         "you'd" =>"you would",
         "you'd've" =>"you would have",
         "you'll" =>"you will",
         "you'll've" =>"you will have",
         "you're" =>"you are",
         "you've" =>"you have",
        );


        $text = str_ireplace(array_keys($contractions),array_values($contractions),$text, $count);
        $iReplaced += $count;

        $relaxed = array(
            "uh"=> "a",
            "acoupla"=> "a couple of",
            "ain'tcha"=> "are you not",
            "algo"=> "I will go",
            "alotta"=> "a lot of",
            "an'"=> "and",
            "'an"=> "than",
            "'ardly"=> "hardly",
            "ayatta"=> "I ought to",
            "atom"=> "at him",
            "awayzaway"=> "a ways away",
            "betcha"=> "bet you",
            "better'an"=> "better than",
            "bleev"=> "believe",
            "'bout"=> "about",
            "brudda"=> "brother",
            "can't"=> "can not",
            "can'tcha"=> "can you not",
            "canna"=> "can not",
            "cara"=> "care of",
            "certainly'd"=> "certainly had",
            "cha"=> "you",
            "chillun"=> "children",
            "'chother"=> "each other",
            "chu"=> "are you",
            "c'mere"=> "come here",
            "c'mon"=> "come on",
            "coulda"=> "could have",
            "couldna"=> "could not have",
            "couldn'ever"=> "could not ever",
            "couldn'it"=> "could it not?",
            "couldn't"=> "could not",
            "could've"=> "could have",
            "could'ja"=> "could you",
            "crect"=> "correct",
            "'cuz"=> "because",
            "d'"=> "the",
            "da"=> "the",
            "dat"=> "that",
            "d'eck"=> "the heck",
            "dem"=> "them",
            "dent"=> "did not",
            "did'ja"=> "did you",
            "didja"=> "did you",
            "didn't"=> "did not",
            "diff'rn't"=> "different",
            "dis"=> "this",
            "d'jeat"=> "did you eat",
            "d'jyava"=> "did you have a",
            "jyhava"=> "did you have a",
            "'drother"=> "I'd rather",
            "'drothers"=> "What I'd rather",
            "druthers"=> "What I'd rather",
            "dodad"=> "do, dad",
            "doin'"=> "doing",
            "don't'cha"=> "do you not",
            "don'tcha"=> "do you not",
            "dunnit"=> "has done it",
            "dunno"=> "do not know",
            "d'yava"=> "do you have a",
            "'er"=> "her",
            "'em"=> "them",
            "fi"=> "if I",
            "figrout"=> "figure out",
            "fulla"=> "full of",
            "fo'"=> "for",
            "for'em"=> "for them",
            "f'yno"=> "if you know",
            "g'bye"=> "good bye",
            "g'by"=> "good bye",
            "g'day"=> "good day",
            "gimme"=> "give me",
            "getcha"=> "get you",
            "gitchu"=> "get you",
            "g'night"=> "good night",
            "gotcha"=> "got you",
            "gotchu"=> "got your",
            "gotcher"=> "got your",
            "gotta"=> "have got to",
            "gunna"=> "going to",
            "gonna"=> "going to",
            "had'n'edn'edn'yet"=> "had not even eaten yet",
            "hafta"=> "have to",
            "has'n'edn'edn'yet"=> "has not even eaten yet",
            "hava"=> "have a",
            "havit"=> "have it",
            "hav'n'edn'edn'yet"=> "have not even eaten yet",
            "hecka"=> "heck of a",
            "heckalota"=> "heck of a lot of",
            "he'd"=> "he would",
            "he'd've"=> "he would have",
            "he'd'a"=> "he would have",
            "here's"=> "here is",
            "he's"=> "he is",
            "he'sn't"=> "he is not",
            "hold'em"=> "hold them",
            "how'ya"=> "how are you",
            "howaya"=> "how are you",
            "how're"=> "how are",
            "howzat"=> "how is that",
            "I'd"=> "I would",
            "I'd've"=> "I would have",
            "I'laftabe"=> "I will have to be",
            "I'll"=> "I will",
            "'im"=> "him",
            "I'm"=> "I am",
            "Ima"=> "I am going to",
            "Imana"=> "I am going to",
            "in'"=> "ing",
            "inna"=> "in a",
            "initiate"=> "and then she ate",
            "isn't"=> "is not",
            "it'll"=> "it will",
            "izzy"=> "is he",
            "jamaican"=> "what'cha makin'",
            "jask"=> "did you ask",
            "jin"=> "are you in",
            "jlike"=> "did you like",
            "ju"=> "do you",
            "'k"=> "o.k.",
            "kinda"=> "kind of",
            "lemme"=> "let me",
            "letcha"=> "let you",
            "let'er"=> "let her",
            "lotta"=> "lot of",
            "m'"=> "my",
            "ma"=> "mom",
            "m'boy"=> "my boy",
            "mighta"=> "might have",
            "mustn't"=> "must not",
            "'n'"=> "and",
            "'net"=> "internet",
            "'neverything"=> "and everything",
            "'night"=> "good night",
            "'nother"=> "another",
            "'nuff"=> "enough",
            "o'"=> "of",
            "o'er"=> "over",
            "offa"=> "off of",
            "o'icy"=> "Oh, I see",
            "omina"=> "I'm going to",
            "or'd"=> "or did",
            "oughta"=> "ought to",
            "outa"=> "out of",
            "outta"=> "out of",
            "pa"=> "dad",
            "'post"=> "supposed",
            "praps"=> "perhaps",
            "prolly"=> "probably",
            "quicker'an"=> "quicker than",
            "robbin'"=> "robbing",
            "'safternoon"=> "this afternoon",
            "'salmost"=> "is almost",
            "'scuse"=> "excuse",
            "she'd"=> "she would",
            "she'd've"=> "she would have",
            "she's"=> "she is",
            "she'sn't"=> "she is not",
            "shoulda"=> "should have",
            "shouldn't've"=> "should not have",
            "shouldna"=> "should not have",
            "shouldn'ever"=> "should not ever",
            "shouldn'it"=> "should it not",
            "shouldn't"=> "should not",
            "should've"=> "should have",
            "should'ja"=> "should you",
            "'sko"=> "let us go",
            "smail"=> "some mail",
            "s'mlunch"=> "some lunch",
            "'smornin'"=> "this morning",
            "snot"=> "it is not",
            "'snothin'"=> "it is nothing",
            "s'nuff"=> "is enough",
            "soda"=> "sort of",
            "soyacan"=> "so you can",
            "somthin'"=> "something",
            "sumthin'"=> "something",
            "sorta"=> "sort of",
            "'splain"=> "explain",
            "'spossible"=> "it is possible",
            "squeat"=> "let us go eat",
            "stuff's"=> "stuff is",
            "summa"=> "some of",
            "'sup"=> "what is up?",
            "t'"=> "to",
            "ta"=> "to",
            "taka"=> "take a",
            "'tar"=> "what are",
            "tater, taters"=> "potato, potatoes",
            "t'day"=> "today",
            "telpu"=> "to help you",
            "temp"=> "temperature",
            "'tever"=> "whatever",
            "there'd"=> "there would",
            "there's"=> "there is",
            "they're"=> "they are",
            "this'll"=> "this will",
            "'tis"=> "it is",
            "'tisn't"=> "it is not",
            "told'ja"=> "told you",
            "toleja"=> "told you",
            "toldja"=> "told you",
            "to've"=> "to have",
            "tryna"=> "are trying to",
            "tseasy"=> "it is easy",
            "tsnot"=> "it is not",
            "'twas"=> "it was",
            "'twasn't"=> "it was not",
            "tweet"=> "to eat",
            "t'yer"=> "to your",
            "wait'll"=> "wait, will",
            "w'all"=> "we all",
            "wanna"=> "want to",
            "wannu"=> "want to",
            "wassamatta"=> "what is the matter?",
            "whazzamatta"=> "what is the matter?",
            "wasson"=> "what is on?",
            "wassup"=> "what is up?",
            "wat'chout"=> "Watch out!",
            "weren't"=> "were not",
            "whaddya"=> "what do you",
            "wuddaya"=> "what do you",
            "whatchamacallit"=> "what you may call it",
            "wuddayacallit"=> "what you may call it",
            "whataya"=> "what are you",
            "whatchu"=> "what do you",
            "whatcha"=> "what do you",
            "what'd"=> "what did",
            "what'll"=> "what will",
            "what're"=> "what are",
            "what's"=> "what is",
            "what'sa"=> "what is the",
            "whatta"=> "what do",
            "whenaya"=> "when are you",
            "whenja"=> "when did you",
            "where'd"=> "where did",
            "where're"=> "where are",
            "whodathunkit"=> "who would have thought it",
            "whodunit"=> "who has done it",
            "whodunit"=> "who has done it",
            "whosure"=> "who is your",
            "widjadidja"=> "with you, did you",
            "wijyadidja"=> "with you, did you",
            "willya"=> "will you",
            "winta"=> "went to",
            "wit'chu"=> "with you",
            "witchu"=> "with you",
            "wanna"=> "want to",
            "wonna"=> "want to",
            "won't"=> "will not",
            "woulda"=> "would have",
            "wouldna"=> "would not have",
            "wouldn't've"=> "would not have",
            "wouldn'ever"=> "would not ever",
            "wouldn'it"=> "would it not?",
            "wouldn't"=> "would not",
            "would've"=> "would have",
            "wud'ja"=> "what did you",
            "wudja"=> "what did you",
            "wuzzat"=> "what is that?",
            "wuzat"=> "what is that?",
            "wuzzis"=> "what is this?",
            "wuzis"=> "what is this?",
            "wuwuzat"=> "what was that?",
            "wuwuzis"=> "what was this?",
            "ya"=> "you",
            "y'ald've"=> "you all would have",
            "y'all"=> "you all",
            "y'almost"=> "you almost",
            "y'also"=> "you also",
            "yar"=> "you are",
            "yarn't"=> "you are not",
            "y'awake"=> "are you awake",
            "y'end"=> "you end",
            "yer"=> "your",
            "yino"=> "yeah, I know",
            "yieno"=> "yeah, I know",
            "yin"=> "you in",
            "yit"=> "you it",
            "y'know"=> "you know",
            "yo'"=> "your",
            "y'off"=> "you off",
            "y'ont"=> "you want",
            "yotta"=> "you ought to",
            "you'laftabe"=> "you will have to be",
            "you'll"=> "you will",
            "young'ns"=> "young ones",
            "you'ns"=> "you all",
            "you're"=> "you are",
            "yoosta"=> "used to",
            "yousta "=> "used to",
            "usta"=> "used to",
            "yout"=> "you out",
            "y'see"=> "you see",
            "y'go"=> "you go",
            "y'understand"=> "you understand",
            "y'up"=> "you up",
            "zit"=> "is it"
        );

        foreach($relaxed as $relaxe => $meaning) {
            $text = preg_replace('/\b'.$relaxe.'\b/i',$meaning,$text,-1,$count);
            $iReplaced += $count;
        }

        $contraction2 = array(
            "'d"=> "would",
            "'da"=> "would have",
            "'s"=> "is",
            "'re"=> "are",
            "'ll"=> "will",
            "n't"=> "not",
            "'d've"=> "would have",
        );

        foreach($relaxed as $relaxe => $meaning) {
            $text = preg_replace('/'.$relaxe.'\b/i',$meaning,$text,-1,$count);
            $iReplaced += $count;
        }

        self::$count_contractions = $iReplaced;

        // bad words
        $badwords = json_decode(file_get_contents(__DIR__.'/../database/seeds/badwords.json'),true);

        foreach(array_keys($badwords) as $badword) {
            $text = preg_replace('/\b'.$badword.'\b/i',' ',$text,-1,$count);
            $iBadWords += $count;
        }

        $badwords = json_decode(file_get_contents(__DIR__.'/../database/seeds/badwords2.json'),true);

        foreach(array_keys($badwords) as $badword) {
            $text = preg_replace('/\b'.$badword.'\b/i',' ',$text,-1,$count);
            $iBadWords += $count;
        }
        self::$count_badwords= $iBadWords;

        return $text;
    }
}

